#-------------------------------------------------------------------------
#               Civilizations 1.4 Configuration
#-------------------------------------------------------------------------
# I Hope you all enjoy this plugin! If you all do, Leave a 5 star review!
# If you all need any support at all Join our discord!!!
# https://discord.gg/PSZS7WnuG2 (This link never expire)
#---------------------------------------------------------------------------
# Permissions
#--------------------------------------------------------------------------
#
#
#
#
#
#-----------------------------------------------------------------------------
# Clan Settings
#-----------------------------------------------------------------------------
Clans-Enabled: true

Max-Clan-Members: 12
Max-Clam-Amount: 300
New-Clan-Fee: 500.0

Clan-Disband-Refund-Enabled: true






#-----------------------------------------------------------------------------
# Kingdom Settings
#-----------------------------------------------------------------------------
Kingdoms-Enabled: true

Max-Kingdoms-Amount: 300
New-Kingdom-Fee: 30000.0

Disband-Refund-Enabled: true

Disband-Refund-Amount: ' '





#-----------------------------------------------------------------------------
# Character Settings
#-----------------------------------------------------------------------------
Character-Card-Enabled: true

Server- Allegiances:
  - 'Air'
  - 'Water'
  - 'Earth'
  - 'Fire'

Server-Races:
  - 'Human'
  - ''
  - ''
  - ''
  - ''

#-----------------------------------------------------------------------------
# Interaction Settings
#-----------------------------------------------------------------------------
Interactions-Enabled: true

#-----------------------------------------------------------------------------
# Bounty Settings
#-----------------------------------------------------------------------------
Bounties-Enabled: true

Server-Bounty-Hunter-Perm: '' #Make sure to fill out, This is used in Broadcast Msgs, Player Msgs, Etc!)


#-----------------------------------------------------------------------------
# Career Settings
#-----------------------------------------------------------------------------
Careers-Enabled: true

#-----------------------------------------------------------------------------
# Custom Character Set Msgs
#-----------------------------------------------------------------------------
Set-Name-Msg: 'You have changed your Name!'
Set-Age-Msg: 'You have changed your Age!'
Set-Gender-Msg: 'You have changed your Gender!'
Set-Height-Msg: 'You have changed your Height!'
Set-Race-Msg: 'You have changed your Race!'
Set-Allegiance-Msg: 'You have changed your Allegiance'
Set-Description-Msg: 'You have changed your Description!'
Set-Male-Msg: 'You are now a Male!'
Set-Female-Msg: 'You are now a Female'
#-----------------------------------------------------------------------------
# Custom Interaction Msgs
#-----------------------------------------------------------------------------
Eat-Msg: 'has eaten some food!'
Drink-Msg: 'has taken a drink!'
Dance-Msg: 'You have started dancing!'
Dance-Broadcast-Msg: 'is busting a move!'
Wave-Msg: 'You have started waving!'
Wave-Broadcast-Msg: 'is waving!'
Shrug-Broadcast-Msg: 'has shrugged'
Laugh-Broadcast-Msg: 'has started laughing'
Yell-Broadcast-Msg: 'has started yelling'
Punch-Broadcast-Msg: 'has punched'
Kick-Broadcast-Msg: 'has kicked'
Slap-Broadcast-Msg: 'has slapped'

#-----------------------------------------------------------------------------
# Custom Player Card Msgs
#-----------------------------------------------------------------------------
Treason-Bounty: '25,000' #default (25,000)
Disband-Price: '0'  #default (0)

Bounty-Msg: 'a bounty will be placed on your head!'
Treason-Msg: 'This is treason, Are you sure you want to continue!'
#-----------------------------------------------------------------------------
# Custom Event Msgs
#-----------------------------------------------------------------------------
Custom-Player-Death-Msg: 'You have died!'

Custom-Bed-Enter-Msg: 'Good Night'
Custom-Bed-Leave-Msg: 'You have slept the night away!'

Custom-Milk-Cow-Msg: 'You have milked a cow!'
Custom-Shear-Sheep-Msg: 'You have sheared the sheep!'