name: Civilization
version: '1.4-SNAPSHOT'
main: com.bigtallahasee.me.civilization.Civilization
authors: [ BigTallahasee ]
commands:
  char:
    description: Allow you to set various rp character details
    aliases: [character, rpcard, id]
  interact:
    description: This will allow you to do
    aliases: [int, i]
  kingdom:
    description: Allows you to perform various kingdom commands
    aliases: [k, nation, empire]
  clan:
    description: Allows you to perform various clan commands
    aliases: [guild, fac, crew]
  civilization:
    description: Main plugin admin features (EX.reload configs, show plugin info, Get plugin support links)
    aliases: [civ]
  careers:
    description: Allows you to perform special careers
    aliases: [biz, work]
  bounty-hunter:
    description: Allows you to perform special commands for the Bounty Hunter career
    aliases: [bh, bail]