#-------------------------------------------------------------------------
#               Civilizations
#-------------------------------------------------------------------------
# I Hope you all enjoy this plugin! If you all do, Leave a 5 star review!
# If you all need any support at all Join our discord!!!
# https://discord.gg/PSZS7WnuG2 (This link never expire)
#---------------------------------------------------------------------------
# Permissions
#--------------------------------------------------------------------------
#
#
#
#
#
#-----------------------------------------------------------------------------
# Clan Settings
#-----------------------------------------------------------------------------
Clans-Enabled: true

Max-Clan-Members: 12
Max-Clam-Amount: 300
New-Clan-Fee: 500.0

Clan-Disband-Refund-Enabled: true


Clan-Name: 'TEMPORARY PARAMETERS'



#-----------------------------------------------------------------------------
# Kingdom Settings
#-----------------------------------------------------------------------------
Kingdoms-Enabled: true

Max-Kingdoms-Amount: 300
New-Kingdom-Fee: 30000.0

Disband-Refund-Enabled: true

Disband-Refund-Amount: ' '





#-----------------------------------------------------------------------------
# Character Settings
#-----------------------------------------------------------------------------
Character-Card-Enabled: true

Server- Allegiances:
  - 'Air'
  - 'Water'
  - 'Earth'
  - 'Fire'

Server-Races:
  - 'Human'
  - ''
  - ''
  - ''
  - ''


#-----------------------------------------------------------------------------
# Bounty Settings
#-----------------------------------------------------------------------------
Bounties-Enabled: true

Server-Bounty-Hunter-Perm: '' #Make sure to fill out, This is used in Broadcast Msgs, Player Msgs, Etc!)


#-----------------------------------------------------------------------------
# Career Settings
#-----------------------------------------------------------------------------
Careers-Enabled: true

#-----------------------------------------------------------------------------
