#-------------------------------------------------------------------------
#               Civilizations
#-------------------------------------------------------------------------
# I Hope you all enjoy this plugin! If you all do, Leave a 5 star review!
# If you all need any support at all Join our discord!!!
# https://discord.gg/PSZS7WnuG2 (This link never expire)
#---------------------------------------------------------------------------
# Permissions
#--------------------------------------------------------------------------
#
#
#
#
#
#-----------------------------------------------------------------------------
# Clan Settings
#-----------------------------------------------------------------------------
Clans-Enabled: true

Max-Clan-Members: 12
Max-Clam-Amount: 300
New-Clan-Fee: 500.0

Clan-Disband-Refund-Enabled: true


Clan-Name: 'TEMPORARY PARAMETERS'



#-----------------------------------------------------------------------------
# Kingdom Settings
#-----------------------------------------------------------------------------
Kingdoms-Enabled: true

Max-Kingdoms-Amount: 300
New-Kingdom-Fee: 30000.0

Disband-Refund-Enabled: true

Disband-Refund-Amount: ' '





#-----------------------------------------------------------------------------
# Character Settings
#-----------------------------------------------------------------------------
Character-Card-Enabled: true






#-----------------------------------------------------------------------------
# Bounty Settings
#-----------------------------------------------------------------------------
Bounties-Enabled: true

Server-Bounty-Hunter-Perm: '' #Make sure to fill out, This is used in Broadcast Msgs, Player Msgs, Etc!)


#-----------------------------------------------------------------------------
# Career Settings
#-----------------------------------------------------------------------------
Careers-Enabled: true



#-----------------------------------------------------------------------------
# Custom Interaction Msgs
#-----------------------------------------------------------------------------
Eat-Msg: 'has eaten some food!'
Drink-Msg: 'has taken a drink!'
Dance-Msg: 'is busting a move!'
Wave-Msg: 'is waving!'

#-----------------------------------------------------------------------------
# Custom Player Card Msgs
#-----------------------------------------------------------------------------
Treason-Bounty: '25,000' #default (25,000)
Disband-Price: '0'  #default (0)

#-----------------------------------------------------------------------------
# Custom Event Msgs
#-----------------------------------------------------------------------------
Custom-Bed-Enter-Msg: 'Good Night'
Custom-Bed-Leave-Msg: 'You have slept the night away!'